services:
  api:
    build: .
    container_name: davivienda-fan-shop-api
    # Optionally tag the built image to reuse/push
    # image: 24bytes/davivienda-fan-shop-api:1.0.1
    restart: always
    ports:
      - '${API_PORT_DOCKER:-3000}:3000'
    environment:
      ENV: ${ENV}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
    volumes:
      # Mount real Firebase credentials at runtime where compiled code expects it
      - ./firebase-credentials.json:/app/dist/firebase-credentials.json:ro
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: davivienda-fan-shop-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
